services: 
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: root 
        POSTGRES_USER: hgallien  
        POSTGRES_DB: db
      ports:
        - "5432:5432"
    adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
